### ISSUE TITLE
About how to upgrade to MacOS 12 with OTA. 微调后可直接OTA更新MacOS12 Monterey

### ISSUE THREAD

**Issue by ske1996** [ske1996/matebook-13-2019-oc-efi#155]
自己给自己提交issue也是绝了……

**Device info（设备信息）**

Matebook 13 2019  

CPU:i7 8th gen  
RAM:8G  
SSD:sn720
MacOS version:11.4 → 12.0db1   
EFI version:0508
OC version:0.6.5

works like in BigSur.
bluetooth and wifi work now.

But you need to do:  
upgrade your lilu and replace your airportitlwm  and intelbluetoothfirmware to lastest ones,
disable intelbuletoothinjector and add bluetoolfix to oc/kexts/ and config.plist.
then,OTA or new-installing your OS with apple's guide.  

so much thanks to [@zxystd](https://github.com/OpenIntelWireless/itlwm)'s great work    

[Monterey IntelBluetooth.zip](https://github.com/ske1996/matebook-13-2019-oc-efi/files/6661815/Monterey.IntelBluetooth.zip)

![Screen Shot 2021-06-08 at 8 57 24 PM](https://user-images.githubusercontent.com/63181546/121292120-6676cf00-c924-11eb-8830-a2e398662ca5.png)
[Monterey IntelBluetooth.zip](https://github.com/ske1996/matebook-13-2019-oc-efi/files/6661815/Monterey.IntelBluetooth.zip)

**Comment by LiuLiujie** [comment]
itlwm+heliport works fine in Monterey

**Comment by ske1996** [comment]
> itlwm+heliport works fine in Monterey

thank you for letting me know that.

**Comment by s3tupw1zard** [comment]
I get a kernel panic.
![IMG_20210710_151345](https://user-images.githubusercontent.com/50152835/125164306-dc738d80-e191-11eb-943a-f3ad6d6e0b30.jpg)
![IMG_20210710_151619](https://user-images.githubusercontent.com/50152835/125164315-e5fcf580-e191-11eb-9559-9f9f5bc23e07.jpg)

**Comment by ske1996** [comment]
> I get a kernel panic on matebook d14 2020.
> 
> ![IMG_20210710_151345](https://user-images.githubusercontent.com/50152835/125164306-dc738d80-e191-11eb-943a-f3ad6d6e0b30.jpg)
> 
> ![IMG_20210710_151619](https://user-images.githubusercontent.com/50152835/125164315-e5fcf580-e191-11eb-9559-9f9f5bc23e07.jpg)
> 
> 
provide following list of info.
1. new-installation or OTA？
2. if OTA,what is your OS version before OTA？
3. if your efi files is from me,which part did you change？
4. put your total log which is print by opencore here.about how to get it,pls google it by yourself.

**Comment by ihxjie** [comment]
蓝牙4.0可用吗？ HUAWEI MOUSE在montery下能否正常使用？

**Comment by ske1996** [comment]
> 蓝牙4.0可用吗？ HUAWEI MOUSE在montery下能否正常使用？

I said at frist."works like in BigSur"
Even you had trid to **read doc more harder**,you wont question like that.
BTW,why dont you upgrade your hackintosh so you can try to figure that out？
And is it so hard to be polite？

**Comment by wrb2012** [comment]
按上面更新蓝牙驱动后 原本不可用的罗技蓝牙鼠标（BT3.0？）也能用了。  目前iCloud设备不可用

**Comment by ihxjie** [comment]
目前我暂时还未使用montery版本，蓝牙文档中对支持的蓝牙的可用性并为做出更多的解释，而在issue中有人提到以前不可使用的蓝牙设备在monterey中可用，所以我来咨询有关新版本macos中华为鼠标的相关问题。另外，我不知道我的问法有什么问题，是哪一句话不礼貌呢？ 发自我的iPhone------------------ 原始邮件 ------------------发件人: ske1996  ***@***.***>发送时间: 2021年7月18日 22:25收件人: ske1996/matebook-13-2019-oc-efi ***@***.***>抄送: ihxjie ***@***.***>, Comment ***@***.***>主题: 回复：[ske1996/matebook-13-2019-oc-efi] About how to upgrade to MacOS 12 with OTA. 微调后可直接OTA更新MacOS12 Monterey (#155)

蓝牙4.0可用吗？ HUAWEI MOUSE在montery下能否正常使用？

I said at frist."works like in BigSur"
Even you had trid to read doc more harder,you wont question like that.
BTW,why dont you upgrade your hackintosh so you can try to figure that out？
And is it so hard to be polite？

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/ske1996/matebook-13-2019-oc-efi/issues/155#issuecomment-882065010",
"url": "https://github.com/ske1996/matebook-13-2019-oc-efi/issues/155#issuecomment-882065010",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ske1996** [comment]
> 目前我暂时还未使用montery版本，蓝牙文档中对支持的蓝牙的可用性并为做出更多的解释，而在issue中有人提到以前不可使用的蓝牙设备在monterey中可用，所以我来咨询有关新版本macos中华为鼠标的相关问题。另外，我不知道我的问法有什么问题，是哪一句话不礼貌呢？ 发自我的iPhone------------------ 原始邮件 ------------------发件人: ske1996 ***@***.***>发送时间: 2021年7月18日 22:25收件人: ske1996/matebook-13-2019-oc-efi ***@***.***>抄送: ihxjie ***@***.***>, Comment ***@***.***>主题: 回复：[ske1996/matebook-13-2019-oc-efi] About how to upgrade to MacOS 12 with OTA. 微调后可直接OTA更新MacOS12 Monterey (#155) 蓝牙4.0可用吗？ HUAWEI MOUSE在montery下能否正常使用？ I said at frist."works like in BigSur" Even you had trid to read doc more harder,you wont question like that. BTW,why dont you upgrade your hackintosh so you can try to figure that out？ And is it so hard to be polite？ —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe. [ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "[#155 (comment)](https://github.com/ske1996/matebook-13-2019-oc-efi/issues/155#issuecomment-882065010)", "url": "[#155 (comment)](https://github.com/ske1996/matebook-13-2019-oc-efi/issues/155#issuecomment-882065010)", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

1. 蓝牙驱动不是我开发的，你来问我这件事本身就很奇怪。我说了但凡你多去看看开发者的文档，你都不会来跟我说这废话。
z大阐明了为什么有的不能用有的能用，原因早就公布了，你以为这种东西都是碰运气？完全没有一点机理在里面？能自己去看的东西为什么要问人呢？首先我讨厌你的懒惰。
2. 说你没礼貌一点都不冤，不是说说脏字了才是没礼貌。你老师没有教你请教人问题的时候应该怎么说话吗？
给你做个示例：作者您好，谢谢你的repo，我想请问xxxx这个问题。麻烦一下，谢谢。

懂了吗？

我看你又懒又说话没礼貌。学学礼仪。
不用再回复我了，看到就会给你删除的。

**Comment by Andresruizj** [comment]
Does anyone know how can repair the audio? i have managed to make everything work except that :/
